### ISSUE TITLE
From scratch build python2.7-pypy7.2.0 error

### ISSUE THREAD

**Issue by walirt** [JayH5/alpine-pypy#33]
halo
I'm trying to build pypy packages from scratch as you did
python and pypy are 2.7 and 7.2.0, respectively
But when I pull to alpine to run, I get the following error 
`
~/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin # ./pypy
Error loading shared library libbz2.so.1: No such file or directory (needed by /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so)
Error loading shared library libexpat.so.1: No such file or directory (needed by /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so)
Error loading shared library libffi.so.6: No such file or directory (needed by /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so)
Error loading shared library libncursesw.so.6: No such file or directory (needed by /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so)
Error relocating /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so: XML_SetUserData: symbol not found
Error relocating /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so: XML_SetUnknownEncodingHandler: symbol not found
Error relocating /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so: XML_ParserCreateNS: symbol not found
Error relocating /root/usession-release-pypy2.7-v7.2.0rc2-1/build/pypy2.7-v7.2.0-linux64-alpine3.9/bin//libpypy-c.so: XML_SetAttlistDeclHandler: symbol not found
...
`
I don't know how to solve it
It took me hours
I hope you can give me some advice. Thank you

**Comment by JayH5** [comment]
Hi @Ri773r,

I'm not sure I can help much right now. I don't use PyPy much these days and am quite busy with other things so I haven't worked on this repo in a while.

I'm not sure what is wrong with your build from that error message. I would suggest using `ldd` to see what the binary is linked against and making sure the correct packages are installed.

I will try find some time, maybe this weekend, to get PyPy 7.2.0 built on Alpine again.

**Comment by walirt** [comment]
> Hi @Ri773r,
> 
> I'm not sure I can help much right now. I don't use PyPy much these days and am quite busy with other things so I haven't worked on this repo in a while.
> 
> I'm not sure what is wrong with your build from that error message. I would suggest using `ldd` to see what the binary is linked against and making sure the correct packages are installed.
> 
> I will try find some time, maybe this weekend, to get PyPy 7.2.0 built on Alpine again.

Thank you very much for your reply
I will continue to focus on this project
And continue to try to solve this problem
Looking forward to your results

**Comment by JayH5** [comment]
I never got around to building PyPy 7.2.0, but I've now built 7.3.0 and all its Docker images. Going to close this issue now, hope your problem is resolved.
